### ISSUE TITLE
Recent changes on master made some code not working properly.

### ISSUE THREAD

**Issue by dennym** [voltrb/volt#274]
Like discussed yesterday on gitter it turns out that my onpage functionality isn't working anymore when using volt@master.
When using a simple e-click events that change attributes on an object. There are no chrome console errors and the server log shows the correct Storetask. But after a refresh the data isn't changed, although the StoreTask in the server console shows the changed data.  

So I checked through the few commits of the last 2 days and it turns out with the ref voltrb/volt@54bdb87 it is still working and with the next one that made changes to the StoreTask (voltrb/volt@97db9dd) it isn't working anymore. 

I made a demo app https://github.com/dennym/ref-diff where you just create some objects with the button and clicking on the listitems unmarks them. After refreshing the page the data is not changed. I have added both refs in the Gemfile for easier testing.

Intended behavior or bug? For me it seems a bug, since the code is pretty straight forward and should work?

best regards

**Comment by ryanstout** [comment]
This should be fixed on master, please reopen if its not.  (I tested and it looks like its working)

**Comment by dennym** [comment]
As mentioned still not working. Also with the recent changes on master.

**Comment by ryanstout** [comment]
@dennym can you explain a bit more what's going on?  (I've got about 50 things going on right now, so its hard for me to keep track of projects and issues :-)
